from pathlib import Path

SOURCE = Path("src/llm_router/zero_cost_router.py")
TESTS = Path("tests/test_model_fallback_resilience.py")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


source = SOURCE.read_text()

old = '''        def add(model: object) -> None:\n            model_id = str(model or "").strip()\n            if model_id and model_id not in candidates:\n                candidates.append(model_id)\n\n        add(preferred)\n        add(self.settings.provider(provider).default_model)\n        for route in self.settings.models.values():\n            if route.provider == provider:\n                add(route.model)\n        cached = self._model_cache.get(provider)\n        if cached:\n            for item in cached[1]:\n                add(item.get("id"))\n        for item in catalog.get(provider, []):\n            add(item.get("model_id"))\n        return candidates\n'''
new = '''        def add(model: object) -> None:\n            model_id = str(model or "").strip()\n            if model_id and model_id not in candidates:\n                candidates.append(model_id)\n\n        def add_discovered(item: dict[str, object], key: str) -> None:\n            model_id = str(item.get(key) or "").strip()\n            if model_id and self._looks_chat_capable_model(model_id, item):\n                add(model_id)\n\n        add(preferred)\n        add(self.settings.provider(provider).default_model)\n        for route in self.settings.models.values():\n            if route.provider == provider:\n                add(route.model)\n        cached = self._model_cache.get(provider)\n        if cached:\n            for item in cached[1]:\n                add_discovered(item, "id")\n        for item in catalog.get(provider, []):\n            add_discovered(item, "model_id")\n        return candidates\n\n    @staticmethod\n    def _looks_chat_capable_model(model_id: str, metadata: dict[str, object]) -> bool:\n        descriptive = " ".join(\n            str(metadata.get(key) or "").lower()\n            for key in (\n                "type", "task", "pipeline_tag", "capability", "capabilities",\n                "modality", "modalities",\n            )\n        )\n        non_chat_terms = (\n            "embedding", "rerank", "speech", "transcription", "text-to-speech",\n            "text_to_speech", "moderation", "image-generation", "image_generation",\n        )\n        if any(term in descriptive for term in non_chat_terms):\n            return False\n\n        lowered = model_id.lower()\n        obvious_non_chat_markers = (\n            "embed", "rerank", "whisper", "tts", "moderation",\n        )\n        return not any(marker in lowered for marker in obvious_non_chat_markers)\n'''
source = replace_once(source, old, new, "chat-capable candidate filter")

old = '''            except ProviderUnavailable as exc:\n                errors.append(f"{name}/{model}: {exc}")\n                if exc.status_code != 413:\n                    self._mark_retryable_failure(name, exc)\n                    failed_providers.add(name)\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=False, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=(time.perf_counter() - t0) * 1000,\n                )\n'''
new = '''            except ProviderUnavailable as exc:\n                errors.append(f"{name}/{model}: {exc}")\n                latency_ms = (time.perf_counter() - t0) * 1000\n                if exc.status_code != 413:\n                    self._mark_retryable_failure(name, exc)\n                    failed_providers.add(name)\n                else:\n                    await self._record_router_event(\n                        provider=name, model=model, stream=False, explicit=explicit,\n                        failover_index=idx, success=False, task_kind=profile.kind,\n                        request_kind=request_kind, latency_ms=latency_ms,\n                        status_code=exc.status_code, request_id=request_id,\n                    )\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=False, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=latency_ms,\n                )\n'''
source = replace_once(source, old, new, "complete 413 failure metrics")

old = '''            except ProviderRequestError as exc:\n                if explicit or exc.status_code != 404:\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=False, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=(time.perf_counter() - t0) * 1000,\n                )\n'''
new = '''            except ProviderRequestError as exc:\n                if explicit or exc.status_code != 404:\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                latency_ms = (time.perf_counter() - t0) * 1000\n                await self._record_router_event(\n                    provider=name, model=model, stream=False, explicit=explicit,\n                    failover_index=idx, success=False, task_kind=profile.kind,\n                    request_kind=request_kind, latency_ms=latency_ms,\n                    status_code=exc.status_code, request_id=request_id,\n                )\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=False, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=latency_ms,\n                )\n'''
source = replace_once(source, old, new, "complete 404 failure metrics")

old = '''            except ProviderUnavailable as exc:\n                if emitted:\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                if exc.status_code != 413:\n                    self._mark_retryable_failure(name, exc)\n                    failed_providers.add(name)\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=True, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=(time.perf_counter() - t0) * 1000,\n                )\n'''
new = '''            except ProviderUnavailable as exc:\n                latency_ms = (time.perf_counter() - t0) * 1000\n                if emitted:\n                    self._mark_retryable_failure(name, exc)\n                    await self._record_router_event(\n                        provider=name, model=model, stream=True, explicit=explicit,\n                        failover_index=idx, success=False, task_kind=profile.kind,\n                        request_kind=request_kind, latency_ms=latency_ms,\n                        status_code=exc.status_code, request_id=request_id,\n                    )\n                    await self._record_message_log(\n                        request_id=request_id, req=req, model=model, stream=True, explicit=explicit,\n                        success=False, request_kind=request_kind, error=exc, provider=name,\n                        status_code=exc.status_code, latency_ms=latency_ms,\n                    )\n                    await self._log_event(\n                        level="warning", source="router",\n                        message=f"provider {name} stream failed after output: {exc}",\n                        provider=name, model=model, request_id=request_id,\n                        details={"status_code": exc.status_code, "partial_response": True},\n                    )\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                if exc.status_code != 413:\n                    self._mark_retryable_failure(name, exc)\n                    failed_providers.add(name)\n                else:\n                    await self._record_router_event(\n                        provider=name, model=model, stream=True, explicit=explicit,\n                        failover_index=idx, success=False, task_kind=profile.kind,\n                        request_kind=request_kind, latency_ms=latency_ms,\n                        status_code=exc.status_code, request_id=request_id,\n                    )\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=True, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=latency_ms,\n                )\n'''
source = replace_once(source, old, new, "stream mid-flight and 413 accounting")

old = '''            except ProviderRequestError as exc:\n                if emitted or explicit or exc.status_code != 404:\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=True, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=(time.perf_counter() - t0) * 1000,\n                )\n'''
new = '''            except ProviderRequestError as exc:\n                if emitted or explicit or exc.status_code != 404:\n                    raise\n                errors.append(f"{name}/{model}: {exc}")\n                latency_ms = (time.perf_counter() - t0) * 1000\n                await self._record_router_event(\n                    provider=name, model=model, stream=True, explicit=explicit,\n                    failover_index=idx, success=False, task_kind=profile.kind,\n                    request_kind=request_kind, latency_ms=latency_ms,\n                    status_code=exc.status_code, request_id=request_id,\n                )\n                await self._record_message_log(\n                    request_id=request_id, req=req, model=model, stream=True, explicit=explicit,\n                    success=False, request_kind=request_kind, error=exc, provider=name,\n                    status_code=exc.status_code, latency_ms=latency_ms,\n                )\n'''
source = replace_once(source, old, new, "stream 404 failure metrics")

SOURCE.write_text(source)

tests = TESTS.read_text()
old = '''        assert hf.calls == []\n        assert router.status["groq"].consecutive_failures == 0\n        await router._metrics_store.close()\n'''
new = '''        assert hf.calls == []\n        assert router.status["groq"].consecutive_failures == 0\n        rows = await router._metrics_store.run_blocking(lambda db: db.get_model_task_metrics(days=30))\n        failed = [row for row in rows if row["provider_name"] == "groq" and row["model"] == "groq-default"]\n        assert failed and failed[0]["attempts"] >= 1 and failed[0]["successes"] == 0\n        await router._metrics_store.close()\n'''
tests = replace_once(tests, old, new, "404 metrics regression")

old = '''async def test_provider_failure_counts_once_even_with_multiple_models(tmp_path) -> None:\n'''
new = '''async def test_non_chat_discovery_models_are_not_fallback_candidates(tmp_path) -> None:\n    async with httpx.AsyncClient() as client:\n        router = ZeroCostModelRouter(_settings(tmp_path), client)\n        router._model_cache["groq"] = (\n            time.time(),\n            [\n                {"id": "groq-default"},\n                {"id": "chat-alt", "type": "chat"},\n                {"id": "text-embedding-3-small", "type": "embedding"},\n                {"id": "whisper-large-v3", "task": "transcription"},\n                {"id": "rerank-v3"},\n            ],\n        )\n\n        candidates = router._provider_model_candidates("groq", "groq-default", {})\n\n        assert "chat-alt" in candidates\n        assert "text-embedding-3-small" not in candidates\n        assert "whisper-large-v3" not in candidates\n        assert "rerank-v3" not in candidates\n        await router._metrics_store.close()\n\n\nasync def test_provider_failure_counts_once_even_with_multiple_models(tmp_path) -> None:\n'''
tests = replace_once(tests, old, new, "non-chat discovery regression")

old = '''        assert any("partial" in line for line in seen)\n        assert first.calls == 1\n        assert second.calls == 0\n        await router._metrics_store.close()\n'''
new = '''        assert any("partial" in line for line in seen)\n        assert first.calls == 1\n        assert second.calls == 0\n        assert router.status["groq"].consecutive_failures == 1\n        events = await router._metrics_store.run_blocking(lambda db: db.get_recent_router_events(limit=10))\n        assert any(\n            event["provider_name"] == "groq"\n            and event["model"] == "groq-default"\n            and event["success"] == 0\n            for event in events\n        )\n        await router._metrics_store.close()\n'''
tests = replace_once(tests, old, new, "mid-stream accounting regression")

TESTS.write_text(tests)
